"""Initial schema

Revision ID: 36141ce4c1f9
Revises: 
Create Date: 2026-03-18 23:18:08.004257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36141ce4c1f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constituencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('chamber', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constituencies_id'), 'constituencies', ['id'], unique=False)
    op.create_index(op.f('ix_constituencies_name'), 'constituencies', ['name'], unique=False)
    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('current_office', sa.String(), nullable=True),
    sa.Column('current_chamber', sa.String(), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_politicians_full_name'), 'politicians', ['full_name'], unique=False)
    op.create_index(op.f('ix_politicians_id'), 'politicians', ['id'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('document_snapshot', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('fetch_timestamp', sa.DateTime(), nullable=False),
    sa.Column('parse_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_records_id'), 'source_records', ['id'], unique=False)
    op.create_table('activity_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=True),
    sa.Column('session_name', sa.String(), nullable=True),
    sa.Column('attendance_count', sa.Integer(), nullable=True),
    sa.Column('debates_count', sa.Integer(), nullable=True),
    sa.Column('questions_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_records_id'), 'activity_records', ['id'], unique=False)
    op.create_table('disclosure_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=True),
    sa.Column('assets', sa.Float(), nullable=True),
    sa.Column('liabilities', sa.Float(), nullable=True),
    sa.Column('criminal_cases', sa.Integer(), nullable=True),
    sa.Column('filing_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disclosure_records_id'), 'disclosure_records', ['id'], unique=False)
    op.create_table('election_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=True),
    sa.Column('constituency_id', sa.Integer(), nullable=True),
    sa.Column('election_year', sa.Integer(), nullable=False),
    sa.Column('party', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_election_records_id'), 'election_records', ['id'], unique=False)
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('chamber', sa.String(), nullable=False),
    sa.Column('term_start', sa.DateTime(), nullable=True),
    sa.Column('term_end', sa.DateTime(), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offices_id'), 'offices', ['id'], unique=False)
    op.create_table('score_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('participation_score', sa.Float(), nullable=False),
    sa.Column('disclosure_score', sa.Float(), nullable=False),
    sa.Column('integrity_risk_adjustment', sa.Float(), nullable=False),
    sa.Column('formula_version', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_records_id'), 'score_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_records_id'), table_name='score_records')
    op.drop_table('score_records')
    op.drop_index(op.f('ix_offices_id'), table_name='offices')
    op.drop_table('offices')
    op.drop_index(op.f('ix_election_records_id'), table_name='election_records')
    op.drop_table('election_records')
    op.drop_index(op.f('ix_disclosure_records_id'), table_name='disclosure_records')
    op.drop_table('disclosure_records')
    op.drop_index(op.f('ix_activity_records_id'), table_name='activity_records')
    op.drop_table('activity_records')
    op.drop_index(op.f('ix_source_records_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_politicians_id'), table_name='politicians')
    op.drop_index(op.f('ix_politicians_full_name'), table_name='politicians')
    op.drop_table('politicians')
    op.drop_index(op.f('ix_constituencies_name'), table_name='constituencies')
    op.drop_index(op.f('ix_constituencies_id'), table_name='constituencies')
    op.drop_table('constituencies')
    # ### end Alembic commands ###
